name: '[Build] main'

on:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref_name }}'
  cancel-in-progress: false

permissions:
  checks: write
  contents: write
  statuses: write
  security-events: write

jobs:
  test:
    name: "Test"
    uses: ./.github/workflows/_test.yaml
    secrets: inherit

  release:
    name: "Release"
    uses: ./.github/workflows/_release.yaml
    needs:
      - test
    secrets: inherit


